name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build for ${{ matrix.board }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        board: [pico, pico2]

    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential

      - name: 'Update Submodules'
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: 'Configure'
        run: |
          cmake -B build-${{ matrix.board }} -S . -DPICO_BOARD=${{ matrix.board }}

      - name: 'Build'
        run: |
          cmake --build build-${{ matrix.board }} --parallel $(nproc)

      - name: 'Upload binary'
        uses: actions/upload-artifact@v4
        with:
          name: uart-bridge-${{ matrix.board }}
          path: build-${{ matrix.board }}/*.uf2
          retention-days: 5
